name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: "Build Java"
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile robot code
      run: ./gradlew build

  test:
    name: "Test Java"
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests on robot code
      run: ./gradlew test -PrunTests

  format:
    name: "Lint and Format Java"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      with:
        fetch-depth: 0
    - name: Fetch all history and metadata
      run: |
        git checkout -b pr
        git branch -f master origin/master
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
    - name: Check output
      run: git --no-pager diff --exit-code HEAD
    - name: Run formatter
      run: ./gradlew build -PwithJavaFormat