name: Comment Commands

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]

# jobs:
#   format:
#     if: github.event.pull_request && startsWith(github.event.comment.body, '/format')
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: Grant execute permission for gradlew
#         run: chmod +x gradlew
      
#       - name: Setup Java
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'temurin'
#           java-version: 17
      
#       - name: React Rocket
#         uses: actions/github-script@v7
#         with:
#           script: |
#             const {owner, repo} = context.issue
#             github.rest.reactions.createForIssueComment({
#               owner,
#               repo,
#               comment_id: context.payload.comment.id,
#               content: "rocket",
#             });
      
#       - name: Run spotlessApply
#         run: ./gradlew spotlessApply
      
#       - name: Commit
#         run: |
#           git config user.name "github-actions[bot]"
#           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git commit -am "Formatting fixes"
#           git push

on:
  issue_comment:
    types: [ created ]

jobs:
  format:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/format')
    runs-on: ubuntu-22.04
    steps:
      - name: React Rocket
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.issue
            github.rest.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.COMMENT_COMMAND_PAT_TOKEN }}
      - name: Fetch all history and metadata
        run: |
          git checkout -b pr
          git branch -f main origin/main
      - name: Checkout PR
        run: |
          gh pr checkout $NUMBER
        env:
          GITHUB_TOKEN: "${{ secrets.COMMENT_COMMAND_PAT_TOKEN }}"
          NUMBER: ${{ github.event.issue.number }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Run spotlessApply
        run: ./gradlew spotlessApply
      - name: Commit
        run: |
          # Set credentials
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Commit
          git commit -am "Formatting fixes"
          git push
