name: Comment Commands

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    if: github.event.pull_request && startsWith(github.event.comment.body, '/format')
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      
      - name: Install wpiformat
        run: pip3 install wpiformat==2024.40
      
      - name: React Rocket
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.issue
            github.rest.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });
      
      - name: Run wpiformat
        run: wpiformat
      
      - name: Run spotlessApply
        run: ./gradlew spotlessApply
      
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Formatting fixes"
          git push
