name: Comment Commands

on:
  issue_comment:
    types: [created]

jobs:
  format:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/format')
    runs-on: ubuntu-22.04
    steps:
      - name: React Rocket
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.issue
            github.rest.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      
      - name: Run spotlessApply
        run: ./gradlew spotlessApply
      
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Formatting fixes"
          git push
